version: "3.9"
volumes:
  php-fpm-socket:
  psysh-store:

networks:
  backend:
  frontend:

services:
  proxy:
    build: 
      context: .
      dockerfile: ./infra/docker/proxy/Dockerfile
    ports:
      - 8140:80 
    depends_on:
      - api-server
      - client
    networks:
      - backend
      - frontend

  api:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-mydatabase}
      - DB_USERNAME=${DB_USER:-myuser}
      - DB_PASSWORD=${DB_PASS:-secret}
    networks:
      - backend

  api-server:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - 8080
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend
    networks:
      - backend
      - frontend

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-8141}:3306
    volumes:
      - type: bind
        source: ./var/mysql
        target: /var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-mydatabase}
      - MYSQL_USER=${DB_USER:-myuser}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
    networks:
      - backend

  client:
    build:
      context: .
      dockerfile: ./infra/docker/nextjs/Dockerfile
      args:
        NODE_ENV: development
    ports:
      - 3000
    volumes:
      - type: bind
        source: ./frontend
        target: /work/frontend
    environment:
      - NODE_ENV=development
    depends_on:
      - api-server
      - api
    networks:
      - backend
      - frontend
    tty: true
