version: "3.9"
volumes:
  php-fpm-socket:
  psysh-store:
  data01:

services:
  api-server:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - 8142:8080
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend

  api:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      - APP_HOST=localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mydatabase
      - DB_USERNAME=myuser
      - DB_PASSWORD=secret

  client:
    build:
      context: .
      dockerfile: ./infra/docker/nextjs/Dockerfile
      args:
        NODE_ENV: development
    ports:
      - 8140:3000
    volumes:
      - type: bind
        source: ./frontend
        target: /work/frontend
    environment:
      - NODE_ENV=development
      - APP_HOST=schedule.me
    depends_on:
      - api-server
      - api
    tty: true

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - 8141:3306
    volumes:
      - type: bind
        source: ./var/mysql
        target: /var/lib/mysql
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

  es01:
    build:
      context: .
      dockerfile: ./infra/docker/elasticsearch/Dockerfile
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 8143:9200

  kib01:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kib01
    ports:
      - 8144:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
